models:
  - type: main
    engine: amazon_bedrock
    parameters:
      model_id: anthropic.claude-v2
      streaming: True

instructions:
  - type: general
    content: |
      Below is a conversation between a human user and an assistant bot. The bot should only greet the user.

#rails:
#  input:
#    flows:
#      - self check input
